{% set version="1.5.1" %}

package:
  name: qimage2ndarray
  version: {{ version }}

source:
  fn: qimage2ndarray-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/q/qimage2ndarray/qimage2ndarray-{{ version }}.tar.gz
  sha256: 5aaf480715436c7820c1ce94c039a0874b7de435274f5b772bd33b1dba0e736f

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - sip
    - pyqt 4.11.*

  run:
    - python
    - numpy
    - sip
    - pyqt 4.11.*

test:
  imports:
    - qimage2ndarray

about:
  home: https://github.com/hmeine/qimage2ndarray
  license: BSD 3-Clause
  summary: Conversion between QImages and numpy.ndarrays.

extra:
  recipe-maintainers:
    - jakirkham
