travis:
  secure:
    BINSTAR_TOKEN: atkqh3Vl1iutIX0mNSYZKhoq3UN9rbT4IcltAI8K9uXPqUSDFMqvNwvHcG/oVv7Shou96C61/Uuj2d1bLvGeXMTP0XVTxxpnnsw5FBqLRz77GqJHpCxbarasjAg41cNiScC77cr9hVgS9AcDbYKxSIQjW+mUVxhVXkpGn91LB6jzkO3T5IcCD6fxQJK5f/Q8qv7V561BwFb2Q6Q+oP36HkMqA4cAC6nxs7IIIVU/AZNM32pyoHlh/rUzV9oSeZ/KJDN7d6/LnxOcGo5O2Uz+50+vUT14UjBrPrW09GYaKC7FNg3IYLUXwe4vL1K1/rJayzDSpjvf0Cp3U+2ijSuKazDoRCruD/T3LP2DAipcuzpTKdLdxlY3+m+sEKX+hl8Utu1NxujJ9vNL6h+9yk8hC4Neu4goAbj0+uVv3k0o4gVxiEKvjn7hEsG4LR0ruI6cPv9i7MByGv/ljsBHLwydpKe/qFjcB9jgQCyL2DQtsUKn1eDBKRQ0fZaNfN15SplQ1w7sUaPWJRn4KXI9vQo4NVZ5TXLt+Odg3cF026Ayz19Tkr2TZdT7F5uKzrXwl/tYcGVjTOyrXlODjgCFw0VGIp0FPS3+fDpD04SLBAdmSwJMxxbyt3NklrSzv5xmywqYx3U97bCIaU896cWuLumImQX/FrBGUSXLM1Lj11KkkXY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
